### ISSUE TITLE
Missing documentation for 90041

### ISSUE THREAD

**Issue by epidemicz** [teisdbr/winlibrs-docs#2]
I was researching error 90041, but I was unable to find it anywhere in the documentation.  I do see it in the error.json file though.

https://github.com/teisdbr/winlibrs-docs/blob/adcd08c9d59861bcd153e03a3d4e5585037658f6/_data/error.json#L3648

**Comment by bttruman** [comment]
Apologies for the delay in response, I apparently didn't have notifications turned on. 

Code was borked on the bit that was supposed to add that Error Code into the documentation. Was set to go on DE 31 instead of DE 14. Fixed with commit 25f750f1b6c2569c36d7e73c8aba16cfb333017e
